[workspace]
resolver = "2"
members = [
    "mangadex-api-types",
    "mangadex-api-schema",
    "mangadex-api",
    "mangadex-api-tests",
    "taurpc-mangadex-api",
    "./taurpc-mangadex-api/examples/taurpc-mangadex-api-example/src-tauri"
]