name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests default
      run: cargo test --all-targets --verbose && cargo test --all-targets -F utils --verbose
    - name: Run tests with `multi-thread`
      run: cargo test --all-targets -F multi-thread --verbose && cargo test --all-targets -F multi-thread,utils --verbose
    - name: Run tests with `tokio-multi-thread`
      run: cargo test --all-targets -F tokio-multi-thread --verbose && cargo test --all-targets -F tokio-multi-thread,utils --verbose